// Generated by Wrangler by running `wrangler types`

interface Env {
	WA_PHONE_NUMBER_ID: string;
	WA_WEBHOOK_TOKEN: string;
	WA_APP_ID: string;
	WA_APP_SECRET: string;
	WA_SYSTEM_ACCESS_TOKEN: string;
}
